version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    command: pnpm dev --host 0.0.0.0
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    ports:
      - 3000:3000
